apiVersion: v1
kind: Service
metadata:
  name: calculator-app-service
  labels:
    app: calculator
spec:
  type: NodePort
  selector:
    project: calculator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30000
        